### ISSUE TITLE
Checking instanceof against Passport.Strategy

### ISSUE THREAD

**Issue by JimtotheB** [jaredhanson/passport-strategy#8]
Trying to check that an object is indeed an instance of Passport.Strategy, I assumed that I could just do this.

```javascript
var Passport = require('passport')
var BearerStrategy = require('passport-http-bearer').Strategy;
var Bearer = new BearerStrategy(//stuff)

console.log(Bearer instanceof Passport.Strategy) //false
```

So barring that, how *can* I check if some object is a passport strategy?

**Comment by jaredhanson** [comment]
JavaScript is dynamically typed.  The only requirement is that it offer a `authenticate` function.  So:

```
if (typeof strategy.authenticate === 'function') {
    // usable as a passport strategy
}
```

What's the use case for doing this type checking?

**Comment by JimtotheB** [comment]
Its for a plugin module that ingests files exporting a function that gets ran through a dependency injector.

Something that looks like this, `User` here is replaced by whatever object is in the injector as 'User', it is ingested by this plugin, https://github.com/Pomegranate/pomegranate-passport/blob/master/index.js, which is in turn ingested by https://github.com/Pomegranate/Pomegranate

```javascript
module.exports = function(User){
  return new BearerStrategy(function(token, done){
    User.findToken(token)
    .then(function(user){
      done(null, user)
    })
  })
};
```

The actual reason for needing to type check them, is so I can differentiate between a Strategy, and an object that contains the user serialization functions (if any).

**Comment by jaredhanson** [comment]
The `instanceof` check is likely because the `Strategy` constructor you are checking against is loaded from a different module than the one use to create the strategy.  This can happen any number of ways, but most likely is because the strategy itself has a dependency on `passport-strategy`, as well as your type checking system.

However, those will be two separate modules, located at different paths under `node_modules`.  As such, they are treated as different objects and the `instanceof` check fails.

This has more to do with JavaScript and module loading, than any thing related to Passport itself.  I suspect you'd see similar behavior with any other "plugable" system that is JavaScript.  As such, using `instanceof` is not a reliable way to check for interfaces.

**Comment by JimtotheB** [comment]
Awesome, thanks a lot for the clarification. I'm using your suggestion in the first case as well as explicitly checking for both of the serialization functions in the other case, so that should cover it well enough. Thanks again for your help.
